name: Notificar Cumpleaños
on:
  schedule:
    - cron: '0 8 * * *'  # Se ejecuta a las 8:00 AM UTC (09:00 AM en España)
  workflow_dispatch:      # Permite ejecutarlo a mano para probar

jobs:
  check-birthdays:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install firebase-admin
      - name: Run script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python notificar_cumples.py
